import Head from 'next/head'
import SideNavbar from "../../components/SideNavbar";

export default function DashboardLayout({ children }) {
    return <>
        <Head>
            <title>Responsive Side-Navbar</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/pro.ico" />
        </Head>
        <SideNavbar />
        {children}
    </>;
}
