import Head from 'next/head'
import SideNavbar from "../../components/SideNavbar";
import axios from 'axios';
import { getServerSession } from "next-auth/next";
import NextAuth, { authOptions } from 'next-auth'

async function callOwnData() {
    const session = await getServerSession(authOptions);
    const { data } = await axios.post(`${process.env.NEXTAUTH_URL}/api/owninfo`, { Correo: session.user.email });
    //console.log(data);
    return data;
}


export default async function DashboardLayout({ children, data }) {

    const ownData = await callOwnData();
    //console.log(ownData);

    return <>
        <Head>
            <title>Responsive Side-Navbar</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/pro.ico" />
        </Head>
        <SideNavbar ownData={ownData} />
        {children}
    </>;
}
